#!/usr/bin/env node
/**
 * Tess project initialization script.
 *
 * Detects how tess is installed (git submodule, git subtree, or symlink)
 * and sets up the tickets/ scaffold and agent-rules references in the host
 * project.
 *
 * Usage:
 *   node tess/scripts/init.mjs              # from project root (submodule/subtree mode)
 *   node /path/to/tess/scripts/init.mjs     # from project root (symlink mode)
 *   node tess/scripts/init.mjs --project /path/to/project
 *
 * Idempotent and non-destructive — safe to re-run at any time.
 */

import { readFile, writeFile, mkdir, symlink, lstat, readlink, access, chmod } from 'node:fs/promises';
import { join, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { constants } from 'node:fs';
import { createInterface } from 'node:readline';
import { spawn } from 'node:child_process';
import { migrate, FORMAT_VERSION } from './migrate.mjs';
import { writeMcpConfig, SUPPORTED_AGENTS } from './lib/mcp-config.mjs';

// ─── Configuration ─────────────────────────────────────────────────────────────

const AGENT_RULE_NAMES = ['AGENTS.md', 'CLAUDE.md'];
const ROOT_AGENT_RULE = 'AGENTS.md';

const TICKET_STAGES = ['backlog', 'fix', 'plan', 'implement', 'review', 'complete', 'blocked'];

const TICKETS_GITIGNORE = '.logs/\n.stop\n.in-progress\n.pre-existing-error.md\n.index/\n';

const STUB_CONTENT = `<!-- Generated by tess init. Do not edit — see tess/agent-rules/tickets.md -->\nRead and follow the ticket workflow rules in [tess/agent-rules/tickets.md](../tess/agent-rules/tickets.md).\n`;

// ─── Helpers ───────────────────────────────────────────────────────────────────

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const TESS_ROOT = resolve(__dirname, '..');

function log(msg) { console.log(`  ${msg}`); }
function warn(msg) { console.warn(`  ⚠ ${msg}`); }

async function exists(path) {
	try { await access(path, constants.F_OK); return true; } catch { return false; }
}

async function isSymlink(path) {
	try { const s = await lstat(path); return s.isSymbolicLink(); } catch { return false; }
}

async function isFile(path) {
	try { const s = await lstat(path); return s.isFile(); } catch { return false; }
}

async function readTextOrEmpty(path) {
	try { return await readFile(path, 'utf-8'); } catch { return ''; }
}

async function writeIfMissing(path, content, label) {
	if (await exists(path)) {
		log(`${label} already exists, skipping`);
		return false;
	}
	await writeFile(path, content, 'utf-8');
	log(`Created ${label}`);
	return true;
}

async function ensureDir(path, label) {
	await mkdir(path, { recursive: true });
}

async function addGitignoreEntry(gitignorePath, entry) {
	const content = await readTextOrEmpty(gitignorePath);
	if (content.split('\n').some(line => line.trim() === entry.trim())) {
		return false;
	}
	const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
	await writeFile(gitignorePath, content + separator + entry + '\n', 'utf-8');
	return true;
}

async function promptYesNo(question, defaultNo = true) {
	const rl = createInterface({ input: process.stdin, output: process.stdout });
	const hint = defaultNo ? '[y/N]' : '[Y/n]';
	return new Promise((resolve) => {
		rl.question(`  ${question} ${hint} `, (answer) => {
			rl.close();
			const a = answer.trim().toLowerCase();
			if (a === '') resolve(!defaultNo);
			else resolve(a === 'y' || a === 'yes');
		});
	});
}

// ─── Detection ─────────────────────────────────────────────────────────────────

/**
 * Determine installation mode.
 * Returns { mode: 'submodule' | 'subtree' | 'symlink', needsRootSymlink: boolean }
 */
async function detectMode(projectRoot) {
	const tessInProject = join(projectRoot, 'tess');

	if (await exists(tessInProject)) {
		if (await isSymlink(tessInProject)) {
			log('Detected: tess is a symlink');
			return { mode: 'symlink', needsRootSymlink: false };
		}

		const dotGitPath = join(tessInProject, '.git');
		if (await isFile(dotGitPath)) {
			const content = await readTextOrEmpty(dotGitPath);
			if (content.includes('gitdir:')) {
				log('Detected: tess is a git submodule');
				return { mode: 'submodule', needsRootSymlink: false };
			}
		}

		// tess/ is a plain directory — check .gitmodules to distinguish
		// submodule (not yet initialized) from subtree / manual copy
		const gitmodulesContent = await readTextOrEmpty(join(projectRoot, '.gitmodules'));
		if (gitmodulesContent.includes('path = tess') || gitmodulesContent.includes('path=tess')) {
			log('Detected: tess is a git submodule (not yet initialized)');
			return { mode: 'submodule', needsRootSymlink: false };
		}

		log('Detected: tess is a git subtree (or plain directory)');
		return { mode: 'subtree', needsRootSymlink: false };
	}

	// tess not in project — running from external path, symlink mode
	log('tess not found in project — will create symlink');
	return { mode: 'symlink', needsRootSymlink: true };
}

// ─── Init steps ────────────────────────────────────────────────────────────────

async function createRootSymlink(projectRoot) {
	const target = relative(projectRoot, TESS_ROOT);
	const linkPath = join(projectRoot, 'tess');

	try {
		await symlink(target, linkPath, 'dir');
		log(`Created symlink: tess → ${target}`);
	} catch (err) {
		if (err.code === 'EPERM' || err.code === 'EACCES') {
			console.error('\nFailed to create symlink (permission denied).');
			console.error('On Windows, enable Developer Mode or run as administrator.');
			process.exit(1);
		}
		throw err;
	}
}

async function createTicketsScaffold(projectRoot, ignoreStages) {
	const ticketsDir = join(projectRoot, 'tickets');

	for (const stage of TICKET_STAGES) {
		await ensureDir(join(ticketsDir, stage));
	}
	log('Ensured tickets/ stage directories');

	await ensureDir(join(ticketsDir, '.logs'));

	let gitignoreContent = TICKETS_GITIGNORE;
	if (ignoreStages) {
		gitignoreContent += TICKET_STAGES.map(s => `${s}/\n`).join('');
	}

	const gitignorePath = join(ticketsDir, '.gitignore');
	if (await exists(gitignorePath)) {
		// Ensure baseline entries are present (covers older .gitignore files
		// from before .index/ was added).
		const baseline = ['.logs/', '.stop', '.in-progress', '.pre-existing-error.md', '.index/'];
		let baselineAdded = false;
		for (const entry of baseline) {
			if (await addGitignoreEntry(gitignorePath, entry)) baselineAdded = true;
		}
		if (baselineAdded) log('Added missing baseline entries to tickets/.gitignore');

		// Update existing .gitignore — add any missing stage entries
		if (ignoreStages) {
			let added = false;
			for (const stage of TICKET_STAGES) {
				if (await addGitignoreEntry(gitignorePath, `${stage}/`)) {
					added = true;
				}
			}
			if (added) log('Added ticket stage folders to tickets/.gitignore');
			else log('tickets/.gitignore already has stage entries, skipping');
		}
	} else {
		await writeFile(gitignorePath, gitignoreContent, 'utf-8');
		log('Created tickets/.gitignore');
	}
}

async function createTicketsStubs(projectRoot) {
	const ticketsDir = join(projectRoot, 'tickets');

	for (const name of AGENT_RULE_NAMES) {
		await writeIfMissing(
			join(ticketsDir, name),
			STUB_CONTENT,
			`tickets/${name}`,
		);
	}
}

async function createTicketsSymlinks(projectRoot) {
	const ticketsDir = join(projectRoot, 'tickets');
	const target = join('..', 'tess', 'agent-rules', 'tickets.md');

	for (const name of AGENT_RULE_NAMES) {
		const linkPath = join(ticketsDir, name);
		if (await exists(linkPath)) {
			log(`tickets/${name} already exists, skipping`);
			continue;
		}
		try {
			await symlink(target, linkPath, 'file');
			log(`Created symlink: tickets/${name} → ${target}`);
		} catch (err) {
			if (err.code === 'EPERM' || err.code === 'EACCES') {
				warn(`Symlink failed for tickets/${name} — falling back to stub file`);
				await writeFile(linkPath, STUB_CONTENT, 'utf-8');
				log(`Created stub: tickets/${name} (symlink fallback)`);
			} else {
				throw err;
			}
		}
	}
}

async function ensureRootAgentRules(projectRoot) {
	const rootSection = await readFile(join(TESS_ROOT, 'agent-rules', 'root.md'), 'utf-8');
	const name = ROOT_AGENT_RULE;
	const filePath = join(projectRoot, name);
	const existing = await readTextOrEmpty(filePath);

	if (existing.includes('## Tickets (tess)')) {
		log(`${name} already has tess section, skipping`);
		return;
	}

	const separator = existing.length > 0 && !existing.endsWith('\n') ? '\n\n' : existing.length > 0 ? '\n' : '';
	await writeFile(filePath, existing + separator + rootSection, 'utf-8');
	log(existing.length > 0 ? `Appended tess section to ${name}` : `Created ${name}`);
}

async function ensureRootSearchRules(projectRoot) {
	const section = await readFile(join(TESS_ROOT, 'agent-rules', 'search.md'), 'utf-8');
	const name = ROOT_AGENT_RULE;
	const filePath = join(projectRoot, name);
	const existing = await readTextOrEmpty(filePath);

	if (existing.includes('## Code search (tess)')) {
		log(`${name} already has code-search section, skipping`);
		return;
	}

	const separator = existing.length > 0 && !existing.endsWith('\n') ? '\n\n' : existing.length > 0 ? '\n' : '';
	await writeFile(filePath, existing + separator + section, 'utf-8');
	log(existing.length > 0 ? `Appended code-search section to ${name}` : `Created ${name}`);
}

async function updateGitignoreForSymlinks(projectRoot) {
	const gitignorePath = join(projectRoot, '.gitignore');
	const entries = ['tess', ...AGENT_RULE_NAMES.map(n => `tickets/${n}`)];

	let added = false;
	for (const entry of entries) {
		if (await addGitignoreEntry(gitignorePath, entry)) {
			added = true;
		}
	}
	if (added) {
		log('Updated .gitignore with tess symlink entries');
	} else {
		log('.gitignore already has tess entries, skipping');
	}
}

// ─── CLI ───────────────────────────────────────────────────────────────────────

function parseArgs(argv) {
	const opts = { projectRoot: process.cwd(), ignoreStages: undefined, withSearch: undefined, withCommitHook: undefined, agent: 'claude' };
	for (let i = 0; i < argv.length; i++) {
		if (argv[i] === '--project' && argv[i + 1]) {
			opts.projectRoot = resolve(argv[++i]);
		} else if (argv[i] === '--ignore-stages') {
			opts.ignoreStages = true;
		} else if (argv[i] === '--no-ignore-stages') {
			opts.ignoreStages = false;
		} else if (argv[i] === '--with-search') {
			opts.withSearch = true;
		} else if (argv[i] === '--no-search') {
			opts.withSearch = false;
		} else if (argv[i] === '--with-commit-hook') {
			opts.withCommitHook = true;
		} else if (argv[i] === '--no-commit-hook') {
			opts.withCommitHook = false;
		} else if (argv[i] === '--agent' && argv[i + 1]) {
			opts.agent = argv[++i];
		} else if (argv[i] === '--help') {
			console.log([
				'Tess project initialization',
				'',
				'Usage:',
				'  node tess/scripts/init.mjs              # submodule or subtree mode',
				'  node /path/to/tess/scripts/init.mjs     # symlink mode',
				'  node tess/scripts/init.mjs --project /path/to/project',
				'',
				'Options:',
				'  --ignore-stages      Add ticket stage folders to .gitignore',
				'  --no-ignore-stages   Keep ticket stage folders tracked in git (default)',
				'  --with-search        Wire MCP code search for the chosen agent',
				'  --no-search          Skip the MCP code search prompt',
				'  --with-commit-hook   Install a post-commit hook that refreshes the index',
				'  --no-commit-hook     Skip the post-commit hook prompt',
				`  --agent <name>       MCP target agent: ${SUPPORTED_AGENTS.join(', ')} (default: claude)`,
				'',
				'Idempotent — safe to re-run at any time.',
			].join('\n'));
			process.exit(0);
		}
	}
	return opts;
}

// ─── Main ──────────────────────────────────────────────────────────────────────

async function main() {
	const opts = parseArgs(process.argv.slice(2));
	const projectRoot = opts.projectRoot;

	console.log(`\nTess init — project: ${projectRoot}`);
	console.log(`            tess:    ${TESS_ROOT}\n`);

	// Verify tess has the expected structure
	const rulesFile = join(TESS_ROOT, 'agent-rules', 'tickets.md');
	if (!await exists(rulesFile)) {
		console.error(`Cannot find ${rulesFile} — is this a valid tess checkout?`);
		process.exit(1);
	}

	const { mode, needsRootSymlink } = await detectMode(projectRoot);

	// Step 1: Create root symlink if needed (symlink mode only)
	if (needsRootSymlink) {
		await createRootSymlink(projectRoot);
	}

	// Step 2: Determine whether to gitignore ticket stage folders
	let ignoreStages = opts.ignoreStages;
	if (ignoreStages === undefined) {
		console.log('');
		console.log('  Ticket stage folders (fix/, plan/, implement/, etc.) can be');
		console.log('  git-ignored if each developer maintains separate tickets.');
		ignoreStages = await promptYesNo('Add ticket stage folders to .gitignore?');
	}

	// Step 3: Create tickets/ scaffold
	await createTicketsScaffold(projectRoot, ignoreStages);

	// Step 4: Create agent-rule references in tickets/
	if (mode === 'submodule' || mode === 'subtree') {
		await createTicketsStubs(projectRoot);
	} else {
		await createTicketsSymlinks(projectRoot);
	}

	// Step 5: Ensure root AGENTS.md / CLAUDE.md have tess section
	await ensureRootAgentRules(projectRoot);

	// Step 6: Update .gitignore (symlink mode only)
	if (mode === 'symlink') {
		await updateGitignoreForSymlinks(projectRoot);
	}

	// Step 7: Stamp/migrate ticket format (handles v1 → v2 if needed)
	const migrateResult = await migrate(join(projectRoot, 'tickets'));
	if (migrateResult.status === 'stamped') {
		log(`Stamped tickets/.version = ${FORMAT_VERSION}`);
	} else if (migrateResult.status === 'migrated') {
		log(`Migrated ${migrateResult.renamed} ticket(s) to format v${FORMAT_VERSION}.`);
	}

	// Step 8: Optional MCP code-search wiring.
	let withSearch = opts.withSearch;
	if (withSearch === undefined) {
		console.log('');
		console.log('  Tess can build a local vector index of the repo and expose it to your');
		console.log('  agent as an MCP `search_code` tool.  No API keys; runs offline.');
		console.log('  This adds a npm install (~150MB incl. native deps) and one model');
		console.log('  download (~80MB) on first use.');
		withSearch = await promptYesNo('Enable MCP code search?');
	}
	if (withSearch) {
		await wireMcpSearch(projectRoot, opts.agent);

		// Step 9: Optional post-commit hook to keep the index fresh.
		let withHook = opts.withCommitHook;
		if (withHook === undefined) {
			console.log('');
			console.log('  A post-commit git hook can refresh the index in the background after');
			console.log('  every commit, so search always reflects HEAD without thinking about it.');
			withHook = await promptYesNo('Install post-commit refresh hook?', false);
		}
		if (withHook) {
			await installCommitHook(projectRoot);
		}
	}

	console.log('\nDone.\n');
}

async function wireMcpSearch(projectRoot, agent) {
	if (!SUPPORTED_AGENTS.includes(agent)) {
		warn(`unknown agent "${agent}" for --with-search; supported: ${SUPPORTED_AGENTS.join(', ')}`);
		return;
	}
	const result = await writeMcpConfig(agent, projectRoot, TESS_ROOT);
	if (result.action === 'unsupported') {
		warn(result.hint);
		return;
	}
	const rel = relative(projectRoot, result.path);
	log(`Wired code-search MCP into ${rel} (${result.action})`);

	await ensureRootSearchRules(projectRoot);

	const installed = await ensureSearchDeps();
	if (!installed) {
		warn('Skipping initial index — install the deps and run `node tess/scripts/index.mjs` manually.');
		return;
	}
	await runInitialIndex(projectRoot);
}

async function ensureSearchDeps() {
	const marker = join(TESS_ROOT, 'node_modules', '.package-lock.json');
	if (await exists(marker)) {
		log('Search deps already installed in tess/node_modules — skipping npm install.');
		return true;
	}
	console.log('');
	log('Installing search deps (npm install in tess/) — this can take ~30s on first run…');
	// npm is a .cmd shim on Windows; Node's post-CVE-2024-27980 spawn refuses to
	// launch .cmd files unless shell:true is set.  Pass the command as a single
	// string so the shell handles tokenization (avoids DEP0190).
	const code = await runShell('npm install', { cwd: TESS_ROOT });
	if (code !== 0) {
		warn(`npm install exited with code ${code}.`);
		return false;
	}
	return true;
}

async function runInitialIndex(projectRoot) {
	console.log('');
	log('Building initial code index (downloads ~80MB model on first run)…');
	// Direct spawn with no shell — process.execPath may contain spaces
	// ("C:\Program Files\nodejs\node.exe"), which a shell would split.
	const code = await runCommand(process.execPath, [
		join(TESS_ROOT, 'scripts', 'index.mjs'),
		'--project', projectRoot,
	], { cwd: projectRoot });
	if (code !== 0) {
		warn(`indexer exited with code ${code} — re-run with: node tess/scripts/index.mjs`);
	}
}

function runCommand(command, args, opts) {
	return new Promise((res, rej) => {
		const child = spawn(command, args, { stdio: 'inherit', shell: false, ...opts });
		child.on('close', code => res(code ?? 0));
		child.on('error', err => rej(err));
	});
}

function runShell(commandLine, opts) {
	return new Promise((res, rej) => {
		const child = spawn(commandLine, { stdio: 'inherit', shell: true, ...opts });
		child.on('close', code => res(code ?? 0));
		child.on('error', err => rej(err));
	});
}

const HOOK_BEGIN = '# >>> tess search index >>>';
const HOOK_END = '# <<< tess search index <<<';
const HOOK_BLOCK = [
	HOOK_BEGIN,
	'# Refresh the local code search index in the background.  Detached so the',
	'# commit feels instant; errors are swallowed (re-run `node tess/scripts/index.mjs`',
	"# manually to surface them).  Remove this block to disable.",
	'( cd "$(git rev-parse --show-toplevel)" && nohup node tess/scripts/index.mjs >/dev/null 2>&1 & ) >/dev/null 2>&1',
	HOOK_END,
].join('\n');

async function installCommitHook(projectRoot) {
	const gitDir = await resolveGitDir(projectRoot);
	if (!gitDir) {
		warn('Could not locate the .git directory — skipping commit hook.');
		return;
	}
	const hooksDir = join(gitDir, 'hooks');
	await mkdir(hooksDir, { recursive: true });
	const hookPath = join(hooksDir, 'post-commit');

	const existing = await readTextOrEmpty(hookPath);
	let next;
	if (existing.length === 0) {
		next = `#!/bin/sh\n${HOOK_BLOCK}\n`;
	} else if (existing.includes(HOOK_BEGIN) && existing.includes(HOOK_END)) {
		next = existing.replace(
			new RegExp(`${escapeRegex(HOOK_BEGIN)}[\\s\\S]*?${escapeRegex(HOOK_END)}`),
			HOOK_BLOCK,
		);
		if (next === existing) {
			log('post-commit hook already up to date');
			return;
		}
	} else {
		const sep = existing.endsWith('\n') ? '' : '\n';
		next = `${existing}${sep}\n${HOOK_BLOCK}\n`;
	}
	await writeFile(hookPath, next, 'utf-8');
	try { await chmod(hookPath, 0o755); } catch { /* Windows: chmod is a no-op anyway */ }
	log(`Installed post-commit hook: ${relative(projectRoot, hookPath)}`);
}

async function resolveGitDir(projectRoot) {
	// `.git` is normally a directory; in submodules and worktrees it's a file
	// of the form `gitdir: <relative-or-absolute path>`.
	const dotGit = join(projectRoot, '.git');
	const stat = await lstat(dotGit).catch(() => null);
	if (!stat) return null;
	if (stat.isDirectory()) return dotGit;
	if (stat.isFile()) {
		const content = await readFile(dotGit, 'utf-8');
		const m = content.match(/^gitdir:\s*(.+)$/m);
		if (!m) return null;
		const target = m[1].trim();
		return resolve(projectRoot, target);
	}
	return null;
}

function escapeRegex(s) {
	return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

main().catch((err) => {
	console.error('Tess init failed:', err);
	process.exit(1);
});
